<!DOCTYPE html>
<html xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<div style="width: 100%"><div id="top-bar" style="margin: 0 auto; "></div></div>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrap">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div id="container">
    	<?php echo ''; ?>

        <div class="inner-container">
            <?php echo $this->getChildHtml('header') ?>
        </div>

        <div class="line-divider"></div>
        <!-- XVCOMM Move to separate phtml later -->

        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
<?php include_once("quantcast_tracking.php"); ?>
</body>
</html>
